# Generated by Django 2.0.10 on 2021-01-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210126_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('title', models.CharField(max_length=240, verbose_name='Name')),
                ('body', models.CharField(max_length=500, verbose_name='body')),
            ],
        ),
    ]
