# Generated by Django 2.0.10 on 2021-03-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('p_id', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
